### ISSUE TITLE
Inconsistent sig figs with values <1

### ISSUE THREAD

**Issue by tjhladish** [BebeSparkelSparkel/to-precision#5]
This is a really nice library.  I think I've found a minor bug:
```
>>> std_notation(0.989999, 3)
'0.990' # good
>>> std_notation(0.999999, 3)
'1.000' # extra sig fig
>>> std_notation(1.0, 3)
'1.00' # good
>>> std_notation(1.00000, 3)
'1.00' # good
>>> std_notation(0.099999, 3)
'0.1000' # extra sig fig
>>> std_notation(0.100000099999, 3)
'0.100' # good
```
Values less than 1 that get rounded up appear to be given an extra digit of precision.  This seems to be because the calculation for 'power' in _number_profile() yields a value that is too big by 1 in these cases.

This seems to have other consequences as well:
```
>>> sci_notation(1.00000,3)
'1.00e0'
>>> sci_notation(0.9999,3)
'10.00e-1'
```
The same issue seems to exist symmetrically for negative numbers.  I don't have a mathematically elegant solution, but conditionally decrementing power before determining sig_digits at the end of _number_profile() seems to work, e.g.:
```
    power = -1 * floor(log10(value)) + precision - 1
    if abs(value) < 1 and (floor(log10(int(round(abs(value) * 10.0**power)))) > floor(log10(int(abs(value) * 10.0**power)))):
        power -= 1
    sig_digits = str(int(round(abs(value) * 10.0**power)))

```
Cheers,
Tom

**Comment by BebeSparkelSparkel** [comment]
@tjhladish Hi Tom.
Thank you so much for finding this!
I really appreciate you providing a solution as well. In the commit listed above I tweaked your solution just a bit and added tests for the problems that you outlined. Could you please take a look at what I have done to ensure that your problem is really fixed?

**Comment by BebeSparkelSparkel** [comment]
@tjhladish Have you had time to look at this yet?

**Comment by tjhladish** [comment]
@BebeSparkelSparkel Sorry for the delay, William.  This doesn't seem to fix the special case--in fact the answers I'm getting are now sometimes mathematically incorrect:
```
>>> from to_precision import *
>>> std_notation(0.989999, 3)
'0.990' # good
>>> std_notation(0.999999, 3)
'10.00' # 10x greater than correct answer, extra sig fig
>>> std_notation(1.999999, 3)
'2.00' # good
>>> std_notation(0.0999999, 3)
'1.000' # same problem as above
```

From a cursory check, it looks like the other notation types reflect the same issue.

Best,
Tom

**Comment by BebeSparkelSparkel** [comment]
I made an error refactoring.
I have also added travis-ci to ensure things are working correctly.
Can you please check if it is working correctly now?

**Comment by BebeSparkelSparkel** [comment]
Everything seems to be passing now.

**Comment by borismul** [comment]
There is still a bug here. 
Try:
std_notation(9.999999999999999e-05, 3). 
'0.00010' #Wrong
std_notation(9.99999999999999e-05, 3). 
'0.000100' #Right

**Comment by borismul** [comment]
I changed this code block:

```
def _number_profile(value, precision):
  '''
  returns:
    string of significant digits
    10s exponent to get the dot to the proper location in the significant digits
    bool that's true if value is less than zero else false

    created by William Rusnack
      github.com/BebeSparkelSparkel
      linkedin.com/in/williamrusnack/
      williamrusnack@gmail.com
    contributions by Thomas Hladish
      github.com/tjhladish
      Issue: github.com/BebeSparkelSparkel/to-precision/issues/5
  '''
  value = float(value)
  is_neg = value < 0
  value = abs(value)

  if value == 0:
    sig_digits = '0' * precision
    power = -(1 - precision)

  else:
    power = -1 * floor(log10(value)) + precision - 1
    
    # issue soved by Thomas Haladish
    # github.com/BebeSparkelSparkel/to-precision/issues/5
    value_power = value * 10.0**power
    if value < 1 and floor(log10(int(round(value_power)))) > floor(log10(int(value_power))):
      power -= 1
    sig_digits = str(int(round(value * 10.0**power))) # cannot use value_power because power is changed

  return sig_digits, int(-power), is_neg
```

into

```
def _number_profile(value, precision):
  '''
  returns:
    string of significant digits
    10s exponent to get the dot to the proper location in the significant digits
    bool that's true if value is less than zero else false

    created by William Rusnack
      github.com/BebeSparkelSparkel
      linkedin.com/in/williamrusnack/
      williamrusnack@gmail.com
    contributions by Thomas Hladish
      github.com/tjhladish
      Issue: github.com/BebeSparkelSparkel/to-precision/issues/5
  '''
  value = float(value)
  is_neg = value < 0
  value = abs(value)

  if value == 0:
    sig_digits = '0' * precision
    power = -(1 - precision)

  else:
    power = -1 * floor(log10(value)) + precision - 1
    
    # issue soved by Thomas Haladish
    # github.com/BebeSparkelSparkel/to-precision/issues/5
    value_power = value * 10.0**power
    if value < 1 and floor(log10(int(round(value_power))) - sys.float_info.epsilon) > floor(log10(int(value_power))):
      power -= 1
    sig_digits = str(int(round(value * 10.0**power))) # cannot use value_power because power is changed

  return sig_digits, int(-power), is_neg
```

Note I subtracted one float machine epsilon in the if statement. Import sys as well in the file

**Comment by BebeSparkelSparkel** [comment]
@borismul Thanks for the report. Can you please move this to a PR so that we can examine it and pull it in when we are satisfied?

**Comment by ghost** [comment]
Why have you added value < 1 as a condition? The same issue applies for bigger numbers also. For example, _number_profile(999, 2) still returns ("100", 2) instead of ("10", 2). Removing the condition value < 1 seems to fix the issue though
